### ISSUE TITLE
downloading

### ISSUE THREAD

**Issue by MohamadSH** [neoxia/laravel-sftp#3]
Hi,
I installed your package I have to say it is amazing. The only problem I have faced is downloading the file. I mean the path function does not work with an SFTP driver so how may I download the file? 
I mean if my SFTP server is xxx.xxx.xxx.xxx may I make a download link using this IP address so the user can download the file straight from the SFTP server?

**Comment by alexandre-butynski** [comment]
Hi @MohamadSH !

An SFTP connection to a hard drive doesn't provide an HTTP access to the files. Then, Laravel or the SFTP driver are not able to provide an URL to the file, this is a non sense.

To expose your file to the web, you have to configure an HTTP access on the file server (for instance, with Nginx) or to pass the file trough the Laravel server. In both options, you will have to track the file path in a custom attribute stored in database.

For the second option, you can imagine something like that :

```PHP
// route
Route::get('files/{key}', 'FileController@show')->where('key', '.*');

// controller
public function show($key)
{
    try {
        $file = $this->storage->get($key);
    } catch (ResourceNotFoundException $e) {
        return Response::view('errors.404', [], 404);
    }

    $keySegments = explode('/', $key);
    $fileName = end($keySegments);

    return Response::download($file, $fileName);
}
```

This is a piece of old school Laravel 4 code but you can see the point !

Hope this helps.
